#! /bin/sh
#

### BEGIN INIT INFO
# Provides: telescoped
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: controls telescope
### END INIT INFO

set -e

PROG="Telescope Server"
DAEMON=/usr/local/sbin/telescope-server
NAME=telescoped
PIDFILE=/var/run/${NAME}.pid
DEFAULTS=/usr/local/etc/default/telescoped

# export variables if the exist in $DEFAULTS
set -a

# check for daemon
test -e $DAEMON || exit 0

# include defaults
[ -r $DEFAULTS ] && . $DEFAULTS

# set PATH
PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH

# get lsb functions
. /lib/lsb/init-functions

start() {
    log_action_begin_msg "Starting $PROG"
    start-stop-daemon --start --quiet --oknodo --background \
	--make-pidfile --pidfile $PIDFILE --startas $DAEMON
}

stop() {
    log_action_begin_msg "Stopping $PROG"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry 10
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	stop
	start
	;;
    status)
	status_of_proc $DAEMON $NAME
	;;
    *)
	log_success_msg "Usage: /etc/init.d/telescoped {start|stop|restart|status}"
	exit 1
esac
